// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeoLvEfuC-69tktP188hHw9B9lRws8h4',
    appId: '1:70518328030:web:2ae58483f931968132104f',
    messagingSenderId: '70518328030',
    projectId: 'coffeesas-b4a7c',
    authDomain: 'coffeesas-b4a7c.firebaseapp.com',
    storageBucket: 'coffeesas-b4a7c.firebasestorage.app',
    measurementId: 'G-TQ1CC0Y59D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Mxv76b1xRAZ7Cg7H10vl6crhHXRg1P0',
    appId: '1:70518328030:android:c50433113de75d4b32104f',
    messagingSenderId: '70518328030',
    projectId: 'coffeesas-b4a7c',
    storageBucket: 'coffeesas-b4a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrqJ5uPBROhHqP4PbuniEMBTIk-PN-7FA',
    appId: '1:70518328030:ios:4b21c153be13a4a532104f',
    messagingSenderId: '70518328030',
    projectId: 'coffeesas-b4a7c',
    storageBucket: 'coffeesas-b4a7c.firebasestorage.app',
    iosBundleId: 'com.example.coffeeSas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrqJ5uPBROhHqP4PbuniEMBTIk-PN-7FA',
    appId: '1:70518328030:ios:4b21c153be13a4a532104f',
    messagingSenderId: '70518328030',
    projectId: 'coffeesas-b4a7c',
    storageBucket: 'coffeesas-b4a7c.firebasestorage.app',
    iosBundleId: 'com.example.coffeeSas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdeoLvEfuC-69tktP188hHw9B9lRws8h4',
    appId: '1:70518328030:web:17607cd5e8c375b432104f',
    messagingSenderId: '70518328030',
    projectId: 'coffeesas-b4a7c',
    authDomain: 'coffeesas-b4a7c.firebaseapp.com',
    storageBucket: 'coffeesas-b4a7c.firebasestorage.app',
    measurementId: 'G-1Y926JT43W',
  );
}
